server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgress:5432/userservice
    username: tech
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect