server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  custom:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437